default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: pokemons_dev

test:
  <<: *default
  database: pokemons_test

production:
  <<: *default
  database: will_be_overwritten_by_heroku
